[build]
  publish = "/"
  command = "echo 'No build needed'"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

# استثناء ملفات .txt من التوجيه
[[redirects]]
  from = "/*.txt"
  to = "/:splat"
  status = 200
  force = true

# توجيه باقي الطلبات إلى index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
